import 'package:get/get.dart';

/// ------------------------
/// TRANSLATIONS
/// ------------------------
class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          // Core Strings
          'sanad_title': 'Sanad',
          'welcome_message': 'Welcome to the Sanad Application',
          // Onboarding
          'onboarding_title1': 'Welcome to Sanad',
          'onboarding_desc1':
              'This app helps you manage your tasks seamlessly.',
          'onboarding_title2': 'Explore Features',
          'onboarding_desc2':
              'Discover powerful tools to boost your productivity.',
          'onboarding_title3': 'Customize Your Experience',
          'onboarding_desc3': 'Select your preferred language and theme.',
          'onboarding_title4': 'Get Started',
          'onboarding_desc4':
              'Begin your journey with Sanad with intuitive instructions!',
          'skip': 'Skip',
          'next': 'Next',
          'get_started': 'Get Started',
          // Login
          'login_title': 'Login',
          'email': 'Email',
          'enter_email': 'Please enter your email',
          'password': 'Password',
          'enter_password': 'Please enter your password',
          'forgot_password': 'Forgot Password?',
          'no_account': "Don't have an account? Register",
          'login': 'Login',
          'login_success': 'Login Successful',
          'login_error': 'Login Error',
          // Register
          'register_title': 'Register',
          'name': 'Name',
          'enter_name': 'Please enter your name',
          "country": "Country",
          "enter_country": "Please enter your country",
          "age": "Age",
          "enter_age": "Please enter your age",
          'password_length': 'Password must be at least 6 characters',
          'register': 'Register',
          'already_account': 'Already have an account? Login',
          'register_success': 'Registration Successful',
          'register_error': 'Registration Error',
          'welcome': 'Welcome',
          // Forgot Password
          'forgot_password_title': 'Forgot Password',
          'reset_password': 'Reset Password',
          'reset_email_sent': 'Reset Email Sent',
          'check_your_email': 'Check your email for reset instructions',
          'error': 'Error',
          // Profile
          'profile': 'Profile',
          'logout': 'Logout',
          "edit_profile": "Edit Profile",
          "profile_updated": "Profile Updated",
          "profile_updated_msg": "Your profile has been updated successfully.",
          "update_error": "Update Error",
          "delete_account": "Delete Account",
          "delete_account_confirm":
              "Are you sure you want to delete your account? This action cannot be undone.",
          "cancel": "Cancel",
          "delete": "Delete",
          "save": "Save",
          // In the 'en_US' map:
          "change_avatar": "Change Avatar",
          "current_password": "Current Password",
          "enter_current_password": "Please enter your current password",
          "new_password": "New Password",
          "enter_new_password": "Please enter your new password",
          "confirm_password": "Confirm Password",
          "enter_confirm_password": "Please confirm your new password",
          "passwords_do_not_match": "Passwords do not match",
          "password_updated": "Password Updated",
          "password_updated_msg":
              "Your password has been updated successfully.",
          "health_info": "Health Information",
          "heart_rate": "Heart Rate",
          "temperature": "Temperature",
          "blood_oxygen": "Blood Oxygen Level",
          "gps_location": "GPS Location",
          "device_info": "Hand-Carried Device Info",
          "battery_level": "Battery Level",
          "connection_status": "Connection Status",
          "device_id": "Device ID",
          "notifications": "Notifications",
          "generate_notification": "Add Notification",
          "no_notifications": "No notifications available.",
          "notification_info_title": "Information",
          "notification_info_body": "General info update.",
          "notification_warning_title": "Warning",
          "notification_warning_body": "Attention needed!",
          "notification_alert_title": "Alert",
          "notification_alert_body": "Critical issue detected!",
          "notification_success_title": "Success",
          "notification_success_body": "Action completed successfully.",
          "notification_health_critical_title": "Critical Health",
          "notification_health_critical_body": "Health situation critical!",
          "notification_temperature_alert_title": "Temperature Alert",
          "notification_temperature_alert_body": "Temperature abnormal!",
          "notification_battery_low_title": "Low Battery",
          "notification_battery_low_body": "Device battery low!",
          "notification_gps_update_title": "GPS Update",
          "notification_gps_update_body": "New location detected.",
          "notification_oxygen_low_title": "Low Oxygen Level",
          "notification_oxygen_low_body": "Blood oxygen low!",
          "notification_heart_rate_alert_title": "Heart Rate Alert",
          "notification_heart_rate_alert_body": "Heart rate abnormal!",
          // Admin Panel
          "admin_panel": "Admin Panel",
          "pilgrims": "Pilgrims",
          "health_notifications": "Health Notifications",
          "medical_services": "Medical Services",
          "device_management": "Device Management",
// Users List
          "users": "Users",
          "search_users": "Search by name or country",
// User Profile Admin
          "user_profile": "User Profile",
          "country": "Country",
          "age": "Age",
          "health_info": "Health Information",
          "heart_rate": "Heart Rate",
          "temperature": "Temperature",
          "blood_oxygen": "Blood Oxygen Level",
          "gps_location": "GPS Location",
          "device_info": "Device Information",
          "battery_level": "Battery Level",
          "connection_status": "Connection Status",
          "device_id": "Device ID",
// Health Notifications
          "health_notif_title_healthy": "All is well",
          "health_notif_body_healthy": "User's vital signs are normal.",
          "health_notif_title_warning": "Warning",
          "health_notif_body_warning": "Some vital signs need attention.",
          "health_notif_title_critical": "Critical Alert",
          "health_notif_body_critical": "User's vital signs are critical!",
// Common
          "notifications": "Notifications",
          "generate_notification": "Generate Notification",
          "no_notifications": "No notifications available.",
// Profile actions
          "logout": "Logout",
          "delete_account": "Delete Account",
          "delete_account_confirm":
              "Are you sure you want to delete your account? This action cannot be undone.",
          "cancel": "Cancel",
          "delete": "Delete",
// Edit Profile & Update Password
          "edit_profile": "Edit Profile",
          "profile_updated": "Profile Updated",
          "profile_updated_msg": "Your profile has been updated successfully.",
          "update_error": "Update Error",
          "change_avatar": "Change Avatar",
          "current_password": "Current Password",
          "enter_current_password": "Please enter your current password",
          "new_password": "New Password",
          "enter_new_password": "Please enter your new password",
          "confirm_password": "Confirm Password",
          "enter_confirm_password": "Please confirm your new password",
          "passwords_do_not_match": "Passwords do not match",
          "password_updated": "Password Updated",
          "password_updated_msg":
              "Your password has been updated successfully.",
          "save": "Save",
// Health Notifications additional
          "health_notifications": "Health Notifications",
// Admin Home (optional)
          "admin_home": "Dashboard",
          "admin_panel": "Admin Panel",
          "welcome": "Welcome",
          "logout": "Logout",
          "delete_account": "Delete Account",
          "pilgrims": "Pilgrims",
          "health_notifications": "Health Notifications",
          "medical_services": "Medical Services",
          "device_management": "Device Management",
          "emergency": "Emergency",
          "warning": "Warning",
          "beds": "beds",
          "calling": "Calling",
          "user_profile": "User Profile",
          "medical_services": "Medical Services",
          "emergency_numbers": "Emergency Numbers",
          "emergency_call": "Emergency Call",
          "ambulance": "Ambulance",
          "civil_defense": "Civil Defense",
          "available_hospitals": "Available Hospitals",
          "calling": "Calling",
          // Example hospital names (if you want them translated)
          "hospital_mena_1": "Mena Hospital",
          "health_center_mena": "Mena Health Center",
          "health_center_muzdalfah": "Muzdalfah Health Center",
          "hospital_arafat": "Arafat General Hospital",
          "health_center_arafat": "Arafat Health Center 21",

          'adminDashboard': 'Admin Dashboard',
          'wearables': 'Wearables',
          'supervisors': 'Supervisors',
          'campaigns': 'Campaigns',
          'createWearable': 'Create Wearable',
          'editWearable': 'Edit Wearable',
          'serialNumber': 'Serial Number',
          'assignedToPilgrimId': 'Assigned To Pilgrim ID',
          'addedByAdminId': 'Added By Admin ID',
          'create': 'Create',
          'update': 'Update',
          'createSupervisor': 'Create Supervisor',
          'editSupervisor': 'Edit Supervisor',
          'name': 'Name',
          'email': 'Email',
          'phone': 'Phone',
          'campaignIds': 'Campaign IDs (comma separated)',
          'createCampaign': 'Create Campaign',
          'editCampaign': 'Edit Campaign',
          'campaignName': 'Campaign Name',
          'region': 'Region',
          'supervisorIds': 'Supervisor IDs (comma separated)',
          'pilgrimIds': 'Pilgrim IDs (comma separated)',
          'Success': 'Success',
          'Error': 'Error',
          'Required': 'Required',
          'Change Language': 'Change Language',
          'Toggle Theme': 'Toggle Theme',
          'adminDashboard': 'Admin Dashboard',
          'statistics': 'Statistics',
          'users': 'Users',
          'pilgrims': 'Pilgrims',
          'campaigns': 'Campaigns',
          'bracelets': 'Bracelets',
          'changeLanguage': 'Change Language',
          'logout': 'Logout',
          'errorLoadingStats': 'Error loading statistics',
          'noStatsAvailable': 'No statistics available',
          'error': 'Error',
          'success': 'Success',
          'requiredField': 'This field is required',
          'invalidEmail': 'Please enter a valid email',
          'passwordTooShort': 'Password must be at least 6 characters',
          'confirmDelete': 'Confirm Delete',
          'delete': 'Delete',
          'cancel': 'Cancel',
          'addUser': 'Add User',
          'editUser': 'Edit User',
          'createUser': 'Create User',
          'username': 'Username',
          'email': 'Email',
          'phone': 'Phone',
          'password': 'Password',
          'role': 'Role',
          'admin': 'Admin',
          'supervisor': 'Supervisor',
          'userCreatedSuccess': 'User created successfully',
          'userUpdatedSuccess': 'User updated successfully',
          'userDeletedSuccess': 'User deleted successfully',
          'errorCreatingUser': 'Error creating user',
          'errorUpdatingUser': 'Error updating user',
          'errorDeletingUser': 'Error deleting user',
          'firebaseAuthError': 'Authentication Error',
          'noUsersFound': 'No users found',
          'areYouSureDeleteUser': 'Are you sure you want to delete user',
          'cannotDeleteSelf': 'You cannot delete your own account',
          'addPilgrim': 'Add Pilgrim',
          'editPilgrim': 'Edit Pilgrim',
          'createPilgrim': 'Create Pilgrim',
          'pilgrimCreatedSuccess': 'Pilgrim created successfully',
          'pilgrimUpdatedSuccess': 'Pilgrim updated successfully',
          'pilgrimDeletedSuccess': 'Pilgrim deleted successfully',
          'errorCreatingPilgrim': 'Error creating pilgrim',
          'errorUpdatingPilgrim': 'Error updating pilgrim',
          'errorDeletingPilgrim': 'Error deleting pilgrim',
          'noPilgrimsFound': 'No pilgrims found',
          'areYouSureDeletePilgrim': 'Are you sure you want to delete pilgrim',
          'personalInformation': 'Personal Information',
          'firstName': 'First Name',
          'middleName': 'Middle Name',
          'lastName': 'Last Name',
          'age': 'Age',
          'gender': 'Gender',
          'male': 'Male',
          'female': 'Female',
          'invalidAge': 'Please enter a valid age',
          'assignmentInformation': 'Assignment Information',
          'campaign': 'Campaign',
          'smartBracelet': 'Smart Bracelet',
          'errorLoadingDropdownData': 'Error loading selection data',
          'pleaseSelectAllRequired': 'Please make selections for all dropdowns',
          'noCampaignsAvailable': 'No campaigns available',
          'noBraceletsAvailable': 'No unassigned bracelets available',
          'serialNumber': 'Serial Number',
          'current': 'Current',
          'Update Your Password': 'Update Your Password',
          'Please fill in your current and new password details to update your password.':
              'Please fill in your current and new password details to update your password.',
          'update_password': 'Update Password',
        },
        'ar_SA': {
          // Core Strings
          'sanad_title': 'سند',
          'welcome_message': 'مرحباً بكم في تطبيق سند',
          // Onboarding
          'onboarding_title1': 'مرحباً بك في سند',
          'onboarding_desc1': 'هذا التطبيق يساعدك على إدارة مهامك بكل سهولة.',
          'onboarding_title2': 'استكشف المزايا',
          'onboarding_desc2': 'اكتشف الأدوات التي تعزز إنتاجيتك.',
          'onboarding_title3': 'خصص تجربتك',
          'onboarding_desc3': 'اختر لغتك وسمة الألوان المفضلة.',
          'onboarding_title4': 'ابدأ الآن',
          'onboarding_desc4': 'ابدأ رحلتك مع سند مع تعليمات ورسوم متحركة!',
          'skip': 'تخطي',
          'next': 'التالي',
          'get_started': 'ابدأ الآن',
          // Login
          'login_title': 'تسجيل الدخول',
          'email': 'البريد الإلكتروني',
          'enter_email': 'يرجى إدخال بريدك الإلكتروني',
          'password': 'كلمة المرور',
          'enter_password': 'يرجى إدخال كلمة المرور',
          'forgot_password': 'نسيت كلمة المرور؟',
          'no_account': 'ليس لديك حساب؟ سجل الآن',
          'login': 'تسجيل الدخول',
          'login_success': 'تم تسجيل الدخول بنجاح',
          'login_error': 'خطأ في تسجيل الدخول',
          // Register
          'register_title': 'التسجيل',
          'name': 'الاسم',
          'enter_name': 'يرجى إدخال اسمك',
          "country": "البلد",
          "enter_country": "يرجى إدخال بلدك",
          "age": "العمر",
          "enter_age": "يرجى إدخال عمرك",
          'password_length': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
          'register': 'تسجيل',
          'already_account': 'هل لديك حساب؟ تسجيل الدخول',
          'register_success': 'تم التسجيل بنجاح',
          'register_error': 'خطأ في التسجيل',
          'welcome': 'أهلاً وسهلاً',
          // Forgot Password
          'forgot_password_title': 'نسيت كلمة المرور',
          'reset_password': 'إعادة تعيين كلمة المرور',
          'reset_email_sent': 'تم إرسال رسالة إعادة التعيين',
          'check_your_email':
              'تحقق من بريدك الإلكتروني لإعادة تعيين كلمة المرور',
          'error': 'خطأ',
          // Profile
          'profile': 'الملف الشخصي',
          'logout': 'تسجيل الخروج',
          "edit_profile": "تعديل الملف الشخصي",
          "profile_updated": "تم تحديث الملف الشخصي",
          "profile_updated_msg": "تم تحديث ملفك الشخصي بنجاح.",
          "update_error": "خطأ في التحديث",
          "delete_account": "حذف الحساب",
          "delete_account_confirm":
              "هل أنت متأكد أنك تريد حذف حسابك؟ لا يمكن التراجع عن هذا الإجراء.",
          "cancel": "إلغاء",
          "delete": "حذف",
          "save": "حفظ",
          // In the 'ar_SA' map:
          "change_avatar": "تغيير الصورة",
          "current_password": "كلمة المرور الحالية",
          "enter_current_password": "يرجى إدخال كلمة المرور الحالية",
          "new_password": "كلمة المرور الجديدة",
          "enter_new_password": "يرجى إدخال كلمة المرور الجديدة",
          "confirm_password": "تأكيد كلمة المرور",
          "enter_confirm_password": "يرجى تأكيد كلمة المرور الجديدة",
          "passwords_do_not_match": "كلمات المرور غير متطابقة",
          "password_updated": "تم تحديث كلمة المرور",
          "password_updated_msg": "تم تحديث كلمة المرور بنجاح.",
          "health_info": "المعلومات الصحية",
          "heart_rate": "معدل ضربات القلب",
          "temperature": "درجة الحرارة",
          "blood_oxygen": "نسبة الأكسجين في الدم",
          "gps_location": "الموقع عبر GPS",
          "device_info": "معلومات الجهاز المحمول",
          "battery_level": "مستوى البطارية",
          "connection_status": "حالة الاتصال",
          "device_id": "معرّف الجهاز",
          "notifications": "الإشعارات",
          "generate_notification": "إضافة إشعار",
          "no_notifications": "لا توجد إشعارات متاحة.",
          "notification_info_title": "معلومات",
          "notification_info_body": "تحديث عام.",
          "notification_warning_title": "تحذير",
          "notification_warning_body": "يتطلب الانتباه!",
          "notification_alert_title": "تنبيه",
          "notification_alert_body": "تم اكتشاف مشكلة حرجة!",
          "notification_success_title": "نجاح",
          "notification_success_body": "تم الإجراء بنجاح.",
          "notification_health_critical_title": "حالة صحية حرجة",
          "notification_health_critical_body": "الحالة الصحية حرجة!",
          "notification_temperature_alert_title": "تنبيه درجة الحرارة",
          "notification_temperature_alert_body": "درجة الحرارة غير طبيعية!",
          "notification_battery_low_title": "البطارية منخفضة",
          "notification_battery_low_body": "بطارية الجهاز منخفضة!",
          "notification_gps_update_title": "تحديث GPS",
          "notification_gps_update_body": "تم اكتشاف موقع جديد.",
          "notification_oxygen_low_title": "الأكسجين منخفض",
          "notification_oxygen_low_body": "مستوى الأكسجين منخفض!",
          "notification_heart_rate_alert_title": "تنبيه ضربات القلب",
          "notification_heart_rate_alert_body": "ضربات القلب غير طبيعية!",
          // Admin Panel
          "admin_panel": "لوحة الإدارة",
          "pilgrims": "الحجاج",
          "health_notifications": "التنبيهات الصحية",
          "medical_services": "الخدمات الطبية",
          "device_management": "إدارة الأجهزة",
// Users List
          "users": "المستخدمون",
          "search_users": "ابحث بالاسم أو البلد",
// User Profile Admin
          "user_profile": "الملف الشخصي",
          "country": "البلد",
          "age": "العمر",
          "health_info": "المعلومات الصحية",
          "heart_rate": "معدل ضربات القلب",
          "temperature": "درجة الحرارة",
          "blood_oxygen": "نسبة الأكسجين في الدم",
          "gps_location": "الموقع عبر GPS",
          "device_info": "معلومات الجهاز",
          "battery_level": "مستوى البطارية",
          "connection_status": "حالة الاتصال",
          "device_id": "معرّف الجهاز",
// Health Notifications
          "health_notif_title_healthy": "كل شيء على ما يرام",
          "health_notif_body_healthy": "المؤشرات الحيوية طبيعية.",
          "health_notif_title_warning": "تحذير",
          "health_notif_body_warning": "بعض المؤشرات تحتاج إلى انتباه.",
          "health_notif_title_critical": "تنبيه حرج",
          "health_notif_body_critical": "المؤشرات الحيوية في حالة حرجة!",
// Common
          "notifications": "الإشعارات",
          "generate_notification": "إنشاء إشعار",
          "no_notifications": "لا توجد إشعارات متاحة.",
// Profile actions
          "logout": "تسجيل الخروج",
          "delete_account": "حذف الحساب",
          "delete_account_confirm":
              "هل أنت متأكد أنك تريد حذف حسابك؟ لا يمكن التراجع عن هذا الإجراء.",
          "cancel": "إلغاء",
          "delete": "حذف",
// Edit Profile & Update Password
          "edit_profile": "تعديل الملف الشخصي",
          "profile_updated": "تم تحديث الملف الشخصي",
          "profile_updated_msg": "تم تحديث الملف الشخصي بنجاح.",
          "update_error": "خطأ في التحديث",
          "change_avatar": "تغيير الصورة",
          "current_password": "كلمة المرور الحالية",
          "enter_current_password": "يرجى إدخال كلمة المرور الحالية",
          "new_password": "كلمة المرور الجديدة",
          "enter_new_password": "يرجى إدخال كلمة المرور الجديدة",
          "confirm_password": "تأكيد كلمة المرور",
          "enter_confirm_password": "يرجى تأكيد كلمة المرور الجديدة",
          "passwords_do_not_match": "كلمات المرور غير متطابقة",
          "password_updated": "تم تحديث كلمة المرور",
          "password_updated_msg": "تم تحديث كلمة المرور بنجاح.",
          "save": "حفظ",
// Health Notifications additional
          "health_notifications": "تنبيهات صحية",
// Admin Home (optional)
          "admin_home": "الرئيسية",
          "admin_panel": "لوحة الإدارة",
          "welcome": "أهلاً",
          "logout": "تسجيل الخروج",
          "delete_account": "حذف الحساب",
          "pilgrims": "الحجاج",
          "health_notifications": "التنبيهات الصحية",
          "medical_services": "الخدمات الطبية",
          "device_management": "إدارة الأجهزة",
          "emergency": "طارئ",
          "warning": "تحذير",
          "beds": "سرير",
          "calling": "جاري الاتصال",
          "user_profile": "الملف الشخصي",
          // Medical Services page
          "medical_services": "الخدمات الطبية",
          "emergency_numbers": "أرقام الطوارئ",
          "emergency_call": "مكالمة طارئة",
          "ambulance": "الإسعاف",
          "civil_defense": "الدفاع المدني",
          "available_hospitals": "المستشفيات المتاحة",
          "calling": "جاري الاتصال",

          // Example hospital names (if needed)
          "hospital_mena_1": "مستشفى منى الوادي",
          "health_center_mena": "مركز صحي منى",
          "health_center_muzdalfah": "مركز صحي مزدلفة",
          "hospital_arafat": "مستشفى عرفات العام",
          "health_center_arafat": "مركز صحي عرفات 21",
          "medical_services": "الخدمات الطبية",
          "emergency_numbers": "أرقام الطوارئ",
          "emergency_call": "مكالمة طارئة",
          "ambulance": "الإسعاف",
          "civil_defense": "الدفاع المدني",
          "available_hospitals": "المستشفيات المتاحة",
          "calling": "جاري الاتصال",
          // Example hospital names
          "hospital_mena_1": "مستشفى منى الوادي",
          "health_center_mena": "مركز صحي منى",
          "health_center_muzdalfah": "مركز صحي مزدلفة",
          "hospital_arafat": "مستشفى عرفات العام",
          "health_center_arafat": "مركز صحي عرفات 21",

          'adminDashboard': 'لوحة الإدارة',
          'wearables': 'الأجهزة القابلة للارتداء',
          'supervisors': 'المشرفون',
          'campaigns': 'الحملات',
          'createWearable': 'إنشاء جهاز قابل للارتداء',
          'editWearable': 'تعديل جهاز قابل للارتداء',
          'serialNumber': 'الرقم التسلسلي',
          'assignedToPilgrimId': 'معرّف الحاج المعين',
          'addedByAdminId': 'أضيف بواسطة معرف المسؤول',
          'create': 'إنشاء',
          'update': 'تحديث',
          'createSupervisor': 'إنشاء مشرف',
          'editSupervisor': 'تعديل المشرف',
          'name': 'الاسم',
          'email': 'البريد الإلكتروني',
          'phone': 'الهاتف',
          'campaignIds': 'معرفات الحملات (مفصولة بفواصل)',
          'createCampaign': 'إنشاء حملة',
          'editCampaign': 'تعديل الحملة',
          'campaignName': 'اسم الحملة',
          'region': 'المنطقة',
          'supervisorIds': 'معرفات المشرفين (مفصولة بفواصل)',
          'pilgrimIds': 'معرفات الحجاج (مفصولة بفواصل)',
          'Success': 'نجاح',
          'Error': 'خطأ',
          'Required': 'مطلوب',
          'Change Language': 'تغيير اللغة',
          'Toggle Theme': 'تبديل النمط',
          'adminDashboard': 'لوحة تحكم المسؤول',
          'statistics': 'الإحصائيات',
          'users': 'المستخدمون',
          'pilgrims': 'الحجاج',
          'campaigns': 'الحملات',
          'bracelets': 'الأساور',
          'changeLanguage': 'تغيير اللغة',
          'logout': 'تسجيل الخروج',
          'errorLoadingStats': 'خطأ في تحميل الإحصائيات',
          'noStatsAvailable': 'لا توجد إحصائيات متاحة',
          'error': 'خطأ',
          'success': 'نجاح',
          'requiredField': 'هذا الحقل مطلوب',
          'invalidEmail': 'الرجاء إدخال بريد إلكتروني صالح',
          'passwordTooShort': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
          'confirmDelete': 'تأكيد الحذف',
          'delete': 'حذف',
          'cancel': 'إلغاء',
          'addUser': 'إضافة مستخدم',
          'editUser': 'تعديل المستخدم',
          'createUser': 'إنشاء مستخدم',
          'username': 'اسم المستخدم',
          'email': 'البريد الإلكتروني',
          'phone': 'رقم الهاتف',
          'password': 'كلمة المرور',
          'role': 'الدور',
          'admin': 'مسؤول',
          'supervisor': 'مشرف',
          'userCreatedSuccess': 'تم إنشاء المستخدم بنجاح',
          'userUpdatedSuccess': 'تم تحديث المستخدم بنجاح',
          'userDeletedSuccess': 'تم حذف المستخدم بنجاح',
          'errorCreatingUser': 'خطأ في إنشاء المستخدم',
          'errorUpdatingUser': 'خطأ في تحديث المستخدم',
          'errorDeletingUser': 'خطأ في حذف المستخدم',
          'firebaseAuthError': 'خطأ في المصادقة',
          'noUsersFound': 'لم يتم العثور على مستخدمين',
          'areYouSureDeleteUser': 'هل أنت متأكد أنك تريد حذف المستخدم',
          'cannotDeleteSelf': 'لا يمكنك حذف حسابك الخاص',
          'addPilgrim': 'إضافة حاج',
          'editPilgrim': 'تعديل حاج',
          'createPilgrim': 'تسجيل حاج',
          'pilgrimCreatedSuccess': 'تم تسجيل الحاج بنجاح',
          'pilgrimUpdatedSuccess': 'تم تحديث بيانات الحاج بنجاح',
          'pilgrimDeletedSuccess': 'تم حذف الحاج بنجاح',
          'errorCreatingPilgrim': 'خطأ في تسجيل الحاج',
          'errorUpdatingPilgrim': 'خطأ في تحديث بيانات الحاج',
          'errorDeletingPilgrim': 'خطأ في حذف الحاج',
          'noPilgrimsFound': 'لم يتم العثور على حجاج',
          'areYouSureDeletePilgrim': 'هل أنت متأكد أنك تريد حذف الحاج',
          'personalInformation': 'المعلومات الشخصية',
          'firstName': 'الاسم الأول',
          'middleName': 'الاسم الأوسط',
          'lastName': 'الاسم الأخير',
          'age': 'العمر',
          'gender': 'الجنس',
          'male': 'ذكر',
          'female': 'أنثى',
          'invalidAge': 'الرجاء إدخال عمر صالح',
          'assignmentInformation': 'معلومات التعيين',
          'campaign': 'الحملة',
          'smartBracelet': 'السوار الذكي',
          'errorLoadingDropdownData': 'خطأ في تحميل بيانات الاختيار',
          'pleaseSelectAllRequired': 'الرجاء تحديد جميع الخيارات المطلوبة',
          'noCampaignsAvailable': 'لا توجد حملات متاحة',
          'noBraceletsAvailable': 'لا توجد أساور غير معينة متاحة',
          'serialNumber': 'الرقم التسلسلي',
          'current': 'الحالي',
          'update_password': 'تحديث كلمة المرور',
          'Update Your Password': 'تحديث كلمة المرور الخاصة بك',
          'Please fill in your current and new password details to update your password.':
              'يرجى ملء بيانات كلمة المرور الحالية والجديدة لتحديث كلمة المرور الخاصة بك.',
          'Update Your Password': 'تحديث كلمة المرور الخاصة بك',
          'Please fill in your current and new password details to update your password.':
              'يرجى ملء بيانات كلمة المرور الحالية والجديدة لتحديث كلمة المرور الخاصة بك.',

          // Settings Screen
          'settings': 'الإعدادات',
          'language': 'اللغة',
          'theme': 'المظهر',
          'account_settings': 'إعدادات الحساب',
        },
      };
}
